version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db
    environment:  
      - POSTGRES_DB=dbangelo
      - POSTGRES_PASSWORD=angelo
      - POSTGRES_USER=angelo
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "80:82"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@gmail.com
      PGADMIN_DEFAULT_PASSWORD: angelo123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
